### PR TITLE
Feat/challenge 1

### PR DESCRIPTION
**Pull request by Daniel94y1**

### CODE REVIEW

**Comment by AdriaCParra** [comment]
Format the code to prettier standarts

**Comment by AdriaCParra** [comment]
Modify route of helpers folder

**Comment by AdriaCParra** [comment]
CHALLENGE-2.md is missing

**Comment by AdriaCParra** [comment]
There are comments in almost all files. DELETE them.

**Review by tictools — APPROVED** [review]

**Review by AdriaCParra — APPROVED** [review]

**Pull request merged**
